# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d8e51f7740c7067c154ec33cc7bfb89a4699958b796debc031b3e809d0b155f1f191e73d203e38c5fb3f8abfa558fac450bd1471eef5bbd04d5032ee172ac4c

test:
  secret_key_base: b7b5be10673d1d240626494f1871929f45ba54d86d7cf133f3f5c6e0d198da41a689d86a78f6b299f291bbe797f85917adcc3165b2375b5a59306935dc6242c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
